apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: rag-s1742390232495
  janus-idp.io/tekton: rag-s1742390232495
  backstage.io/kubernetes-id: rag-s1742390232495
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: rag-s1742390232495
resources:
  - application-dev.yaml
