apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-s1742390232495
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhdh-pai-qe/rag:86459b0fd8074c78e79440c498fb9ec6225b76f1@sha256:3783b93f81afbcd3cf5abfdbd00932acc2259082ba7565b8185cf437180541a6 # use pre-built to bootstrap
          name: app-inference
