apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rag-s1742390232495
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-s1742390232495
  name: rag-s1742390232495
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
