apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: rag-s1742390232495
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-s1742390232495
  name: rag-s1742390232495
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-s1742390232495
